sudo: required

env: 

services:
  - docker

before_install:
  - echo "java"

script:
  - docker login -u $DOCKER_HUB_LOGIN -p $DOCKER_HUB_PASSWORD
  - docker build -t 19931028/homework:v1 -f Dockerfile.static . 
  - docker images
  

job:
  branches:
  only:
  - master
  - stable
