sudo: required

services:
  - docker

env:
  DOCKER_IMAGE_NAME: 19931028/homework/web 

script:
  - |
    docker login -u $DOCKER_HUB_LOGIN -p $DOCKER_HUB_PASSWORD

    # make build
    make docker 

    # Create docker tags for 'latest'
    #if echo "$CI_COMMIT_TAG" | grep -E '^v[0-9]+(\.[0-9]+){2}$'; then
    #  for image in auth sockjs_status_consumer; do
    #    docker tag "$DOCKER_IMAGE_PREFIX/${image}:$CI_COMMIT_TAG" "$DOCKER_IMAGE_PREFIX/${image}:latest"
    #  done
    #fi
    # 
    docker images
    docker push $DOCKER_IMAGE_NAME 

branches:
  only:
  - master
