version: '2'
services:
  static:
    hostname: static
    build:
      context: .
      dockerfile: Dockerfile.static
    environment:
      - VIRTUAL_HOST=*/styles/*.*,*/images/*.*
      - VIRTUAL_HOST_WEIGHT=0
    ports:
      - 80
  web:
    hostname: web
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - 8080
    environment:
      - VIRTUAL_HOST=*/*.action,*/
      - VIRTUAL_HOST_WEIGHT=1
    volumes:
      - ../data:/Users/dcameron/persistence
